version: '3.9'

services:
  db:
    image: postgres
    container_name: reservibe-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: reservibe
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: